-- The interview becomes the first design stage, so every stage under it is written against answers
-- the operator gave rather than against a repository alone.
--
-- Two things move. Every stage a project already holds shifts down one position, because position is
-- the column both stores read the order out of, and a discovery left at 0 would sit where the
-- interview sits. Then every project that already holds a stage gets an interview row marked
-- skipped.
--
-- Skipped rather than empty, because an empty row is a row the rule reads as unsettled: it would
-- refuse every write and every take on a project that was being designed yesterday. A skipped stage
-- counts as settled, so the projects in flight carry on, and the operator runs the interview later.
-- Writing it takes the skip off, and the stages after it then need the word again, which is the rule
-- every stage already carries.
--
-- A project that never staged anything gets nothing. It is designed the way every project was before
-- the stages existed, and a skipped row on it would say somebody decided something.

update project_design_stages
set position = position + 1
where stage <> 'interview';

insert into project_design_stages (id, project, stage, position, skipped)
select
    -- The identifier a row is made with elsewhere is generated by the tool. Here there is no tool, so
    -- it is built from the project, which is unique per row because there is one interview a project.
    'ds-interview-' || p.id,
    p.id,
    'interview',
    0,
    true
from projects p
where exists (select 1 from project_design_stages s where s.project = p.id)
  and not exists (
    select 1 from project_design_stages s where s.project = p.id and s.stage = 'interview');
